<!DOCTYPE html>
<html>
<head>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
</style>
</head>
<body>

<ul>
  <li><a class="active" href="task1.php">Task1</a></li>
  <li><a href="task2.php">Task2</a></li>
  <li><a href="task3.php">Task3</a></li>
  <li><a href="task4.php">Task4</a></li>
  <li><a href="task5.php">Task5</a></li>
  <li><a href="task6.php">Task6</a></li>
  <li><a href="task7.php">Task7</a></li>
  <li><a href="task8.php">Task8</a></li>
  <li><a href="task9.php">Task9</a></li>
  <li><a href="task10.php">Task10</a></li>
</ul>

</body>
</html>
